[build]
  # This command installs the dependencies from your main package.json
  command = "npm install"
  
  # The root of your site (where index.html is)
  publish = "."

  # The directory where your serverless functions live
  functions = "netlify/functions"

[functions]
  # Use the fast esbuild bundler for your functions
  node_bundler = "esbuild"

# This rule makes your function available at a clean URL
[[redirects]]
  from = "/api/generate"
  to = "/.netlify/functions/gemini-proxy"
  status = 200
