[build]
  command = "npm install"
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/generate"
  to = "/.netlify/functions/gemini-proxy"
  status = 200
