[build]
  # بما أن كل الملفات (index.html, etc.) موجودة مباشرة داخل مجلد chat-app
  # الذي سترفعه إلى GitHub، فإن مجلد النشر هو الجذر "."
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

# إعادة توجيه الطلبات من الواجهة الأمامية إلى الدالة السحابية
[[redirects]]
  from = "/api/generate"
  to = "/.netlify/functions/gemini-proxy"
  status = 200
